#!/usr/bin/env python3
"""
Test script for the new pre-made video branding workflow.
"""

import os
from factory.branding import add_branding, add_title_overlay

def test_new_branding_workflow():
    """Test the new workflow with pre-made intro/outro videos."""
    
    print("=== NEW BRANDING WORKFLOW TEST ===")
    print("This tests the new workflow that uses pre-made intro/outro videos")
    print("with title overlay instead of generating slides from scratch.")
    print()
    
    # Test files (we'll create dummy videos for testing)
    main_video = "test_files/video_with_subtitles.mp4"
    intro_video = "test_files/intro.mp4"  # Will use existing intro as test
    outro_video = "test_files/outro.mp4"  # Will use existing outro as test
    
    idea = "Digital privacy and online safety"
    script = "Understanding digital privacy is crucial for staying safe online..."
    output_dir = "test_files"
    
    # Check if test files exist
    files_exist = {
        'main': os.path.exists(main_video),
        'intro': os.path.exists(intro_video), 
        'outro': os.path.exists(outro_video)
    }
    
    print("📁 FILE STATUS:")
    for name, exists in files_exist.items():
        status = "✅ Found" if exists else "❌ Missing"
        print(f"   {name.capitalize()}: {status}")
    print()
    
    if all(files_exist.values()):
        print("🎬 TESTING NEW WORKFLOW:")
        print("1. Generate video title with OpenAI")
        print("2. Add title overlay to intro video")
        print("3. Concatenate: intro_with_title + main + outro")
        print()
        
        result = add_branding(main_video, idea, script, intro_video, outro_video, output_dir)
        
        if result:
            print(f"✅ NEW BRANDING WORKFLOW SUCCESS!")
            print(f"📍 Output: {result}")
            
            if os.path.exists(result):
                file_size = os.path.getsize(result) / (1024 * 1024)  # MB
                print(f"📊 File size: {file_size:.1f} MB")
                
        else:
            print("❌ New branding workflow failed")
            return False
    else:
        print("⚠️  Cannot test - missing required video files")
        print("💡 The new workflow requires:")
        print("   - Pre-made intro.mp4 video (user provides)")
        print("   - Pre-made outro.mp4 video (user provides)")
        print("   - Main content video (generated by pipeline)")
        
    print()
    print("📋 NEW WORKFLOW SUMMARY:")
    print("✓ No more slide generation - uses pre-made videos")
    print("✓ Automatic title overlay on intro video")
    print("✓ Simple concatenation: intro + main + outro")
    print("✓ User has full control over intro/outro design")
    print("✓ Much faster processing")
    
    return True

if __name__ == "__main__":
    test_new_branding_workflow()